export const FETCH_ORDER_LIST_SUCCESS = 'FETCH_ORDER_LIST_SUCCESS';
export const FETCH_ORDER_LIST_FAIL = 'FETCH_ORDER_LIST_FAIL';

export const RESET_FILTERS = 'RESET_FILTERS';
export const SET_SELECTED_FILTER = 'SET_SELECTED_FILTER';